### ISSUE TITLE
お問い合わせ項目のロジック

### ISSUE THREAD

**Issue by uta8a** [hu-hicoder/hicoder-web-projects#10]
お問い合わせ、いらないかも(対応コストがかかるので、gmailだけでよさそう)

**Comment by codesapiens1065** [comment]
@uta8a お問い合わせフォームについてですが，現在ない窓口を増やすのも手間かと思い，お問い合わせフォームに入力された情報についてはGmailに転送してはどうかと考えていたのですが，いかがでしょうか？

**Comment by codesapiens1065** [comment]
@uta8a 承知しました。実装方法を目下検討中です。

**Comment by uta8a** [comment]
良いと思います！その場合、v1ではお問い合わせフォームを消してアカウント名を掲載してくれていると嬉しいです
