### ISSUE TITLE
artifactをGitHubに含めるか決める

### ISSUE THREAD

**Issue by uta8a** [hu-hicoder/hicoder-web-projects#5]
最終的な生成物(今だとHiCoder-site)をどこに置くか

基本的には今のまま素のjs/css/htmlでいくなら、最終的な生成物とコードは同一になるので気にする必要はない。

ただ、GitHub Pagesの制約上、ディレクトリ HiCoder-siteをdocsに名前変更したほうがよい。

**Comment by uta8a** [comment]
これはブランチをreleaseとかにしてやったらよさそうな気がする

**Comment by codesapiens1065** [comment]
@uta8a releaseブランチを切って，ディレクトリ名を"HiCoder-site"から"docs"に変更後，pushしてみましたが，これでよろしいでしょうか？（何やら赤い×が表示されているのですが…）

**Comment by uta8a** [comment]
https://hu-hicoder.github.io/hicoder-web-projects/
GitHub Pages側の設定の問題だったので直しました

**Comment by uta8a** [comment]
releaseブランチで行うことにしたのでclose!
