### ISSUE TITLE
ReactやVueのようなフレームワークを使うか決める

### ISSUE THREAD

**Issue by uta8a** [hu-hicoder/hicoder-web-projects#7]
フレームワークを使うか使わないかの判断

個人的に一番いいと思うのは、まず今のhtml/js/cssでv1としてリリースする(中身の文言は変更する)→React勉強しながらゆっくりv2を作り、リニューアル。みたいな感じ。

@codesapiens1065 ReactとかVue勉強してみたいと言っていたと思うのですが、このへんどうしたいですか？今の状態でも個人的には現行websiteよりはるかに出来がいいので採用してもいいなと思っています。

**Comment by codesapiens1065** [comment]
@uta8a ご提案いただいた通り，「まず今のhtml/js/cssでv1としてリリースする(中身の文言は変更する)→React勉強しながらゆっくりv2を作り、リニューアル」という流れでお願いできればと思います。
