### ISSUE TITLE
使用している写真などのロゴの権利のチェック

### ISSUE THREAD

**Issue by uta8a** [hu-hicoder/hicoder-web-projects#9]
これは @uta8a が担当する

**Comment by uta8a** [comment]
よく考えたらImageの出処が分からなかった。
@codesapiens1065 
`assets/img/` 以下の画像の出典をそれぞれ教えてくれると助かります！

**Comment by codesapiens1065** [comment]
- [image-1.jpg](https://unsplash.com/photos/SYTO3xs06fU)
- [image-2.jpg](https://unsplash.com/photos/XJXWbfSo2f0)
- [image-3.jpg](https://unsplash.com/photos/FO7JIlwjOtU)
- [image-about.jpg](https://unsplash.com/photos/tysecUm5HJA)
- [image-recruitment.png](https://www.freepik.com/free-vector/great-isometric-user-experience_851898.htm)

**Comment by uta8a** [comment]
チェックはクリアしたのでclose
